### ISSUE TITLE
Error msg

### ISSUE THREAD

**Issue by TomKoester** [phev8/ward-metrics#3]
Hello im trying to use your eval_events method. The example from your documentation is working. If im using it on my data:
Ground Truth:
[(0, 60), (61, 74), (75, 76), (77, 89), (90, 91), (92, 100), (101, 101), (102, 111), (112, 113), (114, 126), (127, 128), (129, 140), (141, 141), (142, 149), (150, 151), (152, 164), (165, 165), (166, 177), (178, 179), (180, 189), (190, 191), (192, 202), (203, 204), (205, 213), (214, 215), (216, 231), (232, 233), (234, 253), (254, 255), (256, 265), (266, 267), (268, 277), (278, 278), (279, 287), (288, 288), (289, 309), (310, 311), (312, 318), (319, 327)]
Pred:
[(0, 0), (1, 59), (60, 74), (75, 76), (77, 82), (83, 83), (84, 89), (90, 91), (92, 100), (101, 102), (103, 109), (110, 110), (111, 111), (112, 112), (113, 113), (114, 126), (127, 128), (129, 140), (141, 141), (142, 150), (151, 151), (152, 164), (165, 165), (166, 177), (178, 178), (179, 189), (190, 191), (192, 202), (203, 204), (205, 205), (206, 213), (214, 215), (216, 231), (232, 233), (234, 253), (254, 254), (255, 255), (256, 265), (266, 266), (267, 267), (268, 277), (278, 278), (279, 286), (287, 287), (288, 288), (289, 309), (310, 310), (311, 311), (312, 318), (319, 320), (321, 327)]

im getting the error msg 
File "C:\Users\PycharmProjects\CT2\venv\lib\site-packages\wardmetrics\core_methods.py", line 412, in compute_event_scores
    if det_event_scores[j] == "M'" or det_event_scores[j] == "M'F'":
IndexError: list index out of range

Can you please provide a solution? I think there is a logical bug in the Core methods implementation.

Thanks

**Comment by phev8** [comment]
Hello,
it seems like the issue is that you have a bunch of zero length events in your lists, and apparently the methods are not equipped to deal with such - if I remember correctly, those are useless in this evaluation anyways (it's a while ago I implemented this...) 

So if you remove all entries from your list where the two number in your tuple are equal (e.g. (101,101), (141, 141) ... (0, 0), ... etc.) it would run.

Additionally, I think you covered the whole segment range from 0 to 327 with segments, and I don't believe this is intended to be. Events (e.g. ground truth), should be like:
- observation period: 0-327
- activity/event happened: (10-15), (65-78), etc. (so you only mark the activity, and don't mark when nothing happened (background) 
If you have multi class problem, you filter the events for a specific label first.

I hope this helps go around the mentioned problem. The methods could probably deal with the issue more gracefully, and provide a better fitting error message, so thanks for reporting.

**Comment by TomKoester** [comment]
Hey,
your answer were rly helpful and now its all working as intended. Thank you for your fast responds!
